Add NationalId
lana/b2c-mapp-ui-assets pull request #25
Opened 2020-08-25 16:27 UTC by JoseOrtiz

## Description
KYC needs an illustration not present which is National ID

## Checks
- [x] Requires documentation update
- [ ] Requires lib version update

## Versioning impact
- [ ] **MAJOR** incompatible API changes.
- [ ] **MINOR** adds functionality in a backwards-compatible manner.
- [x] **PATCH** backwards-compatible bug fixes.

2020-08-25 18:09 UTC, rahulpsingh approved these changes

2020-08-26 06:04 UTC, jantocv commented
@JoseOrtiz please could you confirm that this icon is not the same as `details.svg` file? Thanks.

2020-08-26 06:08 UTC, jasonadt requested changes

2020-08-26 06:08 UTC, jasonadt commented on src/icons/nationalId.svg
> +<svg viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
Please add the missing `class="icon"` attribute to this line.

2020-08-26 11:31 UTC, JoseOrtiz commented
> @JoseOrtiz please could you confirm that this icon is not the same as `details.svg` file? Thanks.

Yeah, it's the same, but it's a very bad name for a ID type icon

2020-08-26 11:32 UTC, jasonadt commented
> > @JoseOrtiz please could you confirm that this icon is not the same as `details.svg` file? Thanks.
> 
> Yeah, it's the same, but it's a very bad name for a ID type icon

Then let's please make sure keep only one and remove the other one.

2020-08-26 11:34 UTC, closed without merging